#!/bin/sh
#
# runtests all = run all tests even if they fail
# runtests force = force-pass all tests, note the outputs
#

export PATH=".:$PATH"
DOPASS=$1
for ATEST in `ls tests/run`; do
  printf "$ATEST: "
  ADIFF=`sh tests/run/$ATEST 2>&1 | diff -c tests/out/$ATEST /dev/stdin`
  if [ "$?" = "2" ]; then
    if [ "x${DOPASS}" = "x" ]; then
      ADIFF="NO GOOD OUTPUT"
    else
      sh passtest $ATEST
      ADIFF=`sh tests/run/$ATEST 2>&1 | diff -c tests/out/$ATEST /dev/stdin`
    fi
  fi
  if [ "x${ADIFF}" = "x" ]; then
    echo "OK"
  else
    echo "FAIL"
    echo "${ADIFF}"
    if [ "x${DOPASS}" = "x" ]; then
      echo "Exiting"
      exit 1
    else
      if [ "x${DOPASS}" = "xforce" ]; then
        sh passtest $ATEST
        ADIFF=`sh tests/run/$ATEST 2>&1 | diff -c tests/out/$ATEST /dev/stdin`
      fi
    fi
  fi
done
exit 0 
